version: '3'
networks:
  arsch:

services:
  db:
    restart: unless-stopped
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        - MARIADB_NAME=${MARIADB_NAME}
        - MARIADB_USER=${MARIADB_USER}
        - MARIADB_PWD=${MARIADB_PWD}
        - MARIADB_ROOT_PWD=${MARIADB_ROOT_PWD}
    image: mariadb
    container_name: mariadb
    environment:
      - TZ=Europe/Berlin
    expose:
      - 3306
    networks:
      arsch:
    volumes:
      - wordpress_db:/var/lib/mysql:z
#    healthcheck:
#      test: mysql -u root -e "SELECT VERSION();"

  wordpress:
    depends_on:
      - db
#     db:
#        condition: service_healthy
    restart: unless-stopped
    build:
      context: ./requirements/wordpress_phpfpm
      dockerfile: Dockerfile
    image: wordpress
    container_name: wordpress
    environment:
      - TZ=Europe/Berlin
    networks:
      arsch:
    volumes:
      - wordpress_data:/some/where/over/the/rainbow:z
    env_file: .env

#  nginx:
#    depends_on:
#      - wordpress
#   restart: unless-stopped
#   build:
#     context: ./requirements/nginx
#     dockerfile: Dockerfile
#     args:
#       - A=A
#   image: nginx
#   container_name: nginx
#   environment:
#     - TZ=Europe/Berlin
#   expose:
#     - 443
#   networks:
#     arsch:
#   volumes:
#     - wordpress_data:/some/where/over/the/rainbow:z

  raven:
    restart: unless-stopped
    build: ./requirements/bonus/raven
    image: raven
    container_name: raven
    environment:
      - TZ=Europe/Berlin
    expose:
      - 4242
    networks:
      arsch:
    volumes:
      - "/home/mhahn/srcs/requirements/bonus/raven/melian:/home/admin/melian:Z"

volumes:
  wordpress_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/mhahn/data/wordpress-db"

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/mhahn/data/wordpress-data"
