version: '3'
networks:
  arsch:
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1

services:
  mariadb:
    restart: unless-stopped
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        - MARIADB_NAME=${MARIADB_NAME}
        - MARIADB_USER=${MARIADB_USER}
        - MARIADB_PWD=${MARIADB_PWD}
    image: mariadb
    container_name: mariadb
    environment:
      - TZ=Europe/Berlin
    expose:
      - 3306
    networks:
      arsch:
        ipv4_address: 172.20.0.3
    volumes:
      - wordpress_db:/var/lib/mysql:z

  wordpress:
    depends_on:
      - mariadb
    restart: unless-stopped
    build:
      context: ./requirements/wordpress_phpfpm
      dockerfile: Dockerfile
      args:
        - A=A
    image: wordpress
    container_name: wordpress
    environment:
      - TZ=Europe/Berlin
    expose:
      - 9000
    networks:
      arsch:
        ipv4_address: 172.20.0.4
    volumes:
      - wordpress_data:/some/where/over/the/rainbow:z

  nginx:
    depends_on:
      - wordpress
    restart: unless-stopped
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
      args:
        - A=A
    image: nginx
    container_name: nginx
    environment:
      - TZ=Europe/Berlin
    expose:
      - 443
    networks:
      arsch:
        ipv4_address: 172.20.0.5
    volumes:
      - wordpress_data:/some/where/over/the/rainbow:z

  raven:
    restart: unless-stopped
    build: ./requirements/bonus/raven
    image: raven
    container_name: raven
    environment:
      - TZ=Europe/Berlin
    expose:
      - 4242
    networks:
      arsch:
        ipv4_address: 172.20.0.2
    volumes:
      - "/home/mhahn/srcs/requirements/bonus/raven/melian:/home/admin/melian:Z"

volumes:
  wordpress_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/mhahn/data/wordpress-db"

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/mhahn/data/wordpress-data"
